import { hash } from 'bcryptjs';

import type { NextFunction, Request, Response } from 'express';
import type { Deck, FriendInvite, User, ValidationReturn } from '../lib/types.ts';

import { formValidation, generateUsername } from '../lib/utils.ts';
import { SignUpSchema, AddFriendSchema } from '../lib/schemas.ts';
import { getDb } from '../src/db.ts';
import { ObjectId } from 'mongodb';
import { getUser } from '../src/queries.ts';

export async function signUpController(req: Request, res: Response): Promise<void> {

  // Validating data
  const validationResult = formValidation(SignUpSchema, req.body);

  // If validation failed
  if ('errors' in validationResult) {
    res.status(400).json(validationResult);
    return // finalize the function
  }

  // If validation went through
  const { email, password } = validationResult as ValidationReturn;

  // Getting the database instance
  let db = await getDb();
  if (!db) throw new Error(`Couldn't get database from multiplayer controller`);
  
  // Check if there is a user with the same email
  const duplicateEmail = await getUser({ email: email })
  if (duplicateEmail) {
    res.status(400).json({ errors: ['This email is already being used'] });
    return // finalize the function
  }

  const defaultDeck = await db.collection<Deck>('decks').findOne({ name: 'The Resistance' });
  if (!defaultDeck) throw new Error(`Couldn't find the default deck → ${defaultDeck}`)

  const hashedPassword = await hash(password, 10);
  
  const autoGeneratedUsername = generateUsername(email);

  const userObj: User = {
    // User id is created when it is inserted for the first time in the database
    username: autoGeneratedUsername,
    email: email,
    password: hashedPassword,
    avatar: 'knight',
    friends: [], 
    deck_id: defaultDeck._id,
    friend_invites: [],
  }

  // Adds brand new user to db
  await db
    .collection('users')
    .insertOne(userObj)

  res.status(200).json({ success: true });
  return; // finalize the function
}

export function checkAuthController(req: Request, res: Response, next: NextFunction): void {
  const userObject = req.user;
  if (!userObject) {
    res.json({ message: 'No user logged in' })
    next();
    return; // Stop function execution
  }

  // Send serialized user to the client
  res.status(200).json({ user: userObject });
}

export async function logOutController (req: Request, res: Response, next: NextFunction): Promise<void> {
  if (!req.user) {
    next(new Error(`Occurred an error with user`));
    return;
  }

  const db = await getDb();
  const sessionId = req.sessionID;

  if (!sessionId) {
     next(new Error(`Occurred an error with the session ID`));
     return;
  };

  // Delete the session from the database
  await db.collection('sessions').deleteOne({ _id: sessionId as any })

  // Logging the user out
  req.logout((err) => {
    if (err || !req.user)
      next(err);
    res.status(200).json({ success: true });
  });

  return
}

export async function addFriendInvite(req: Request, res: Response): Promise<void> {
  const validationResult = formValidation(AddFriendSchema, req.body);

  // If validation failed
  if ('errors' in validationResult) {
    res.status(400).json(validationResult);
    return // finalize the function
  };

  const recipientUser = await getUser({ username: validationResult.friendUsername })

  // Sending a response based if the user exists or not
  if (recipientUser) {
    const senderUser = await getUser({ username: validationResult.senderUsername })
    if (senderUser) {

      // Inserting the friend invite object into the database user objects
      const inviteObj = {
        recipient: recipientUser.username,
        sender: senderUser.username,
        to: recipientUser._id as ObjectId,
        from: senderUser._id as ObjectId,
        status: 2 as (0 | 1 | 2) // Pending
      }

      const db = await getDb();

      // Storing the users collection in a variable
      const users = db.collection<User>('users');

      // Updating the sender's friend invites array
      await users.updateOne(
        { _id: senderUser._id as ObjectId }, 
        { $push: { friend_invites: inviteObj } }
      )
      
      // Updating the recipientUser's friend invites array
      await users.updateOne(
        { _id: recipientUser._id as ObjectId }, 
        { $push: { friend_invites: inviteObj } }
      )
      
      res.status(200).json({ success: true, invite: inviteObj })
    }
  } else {
    res.status(400).json({ success: false, errors: [`This username doesn't exist`] })
  }

  return
}

export async function acceptFriendInvite(req: Request, res: Response): Promise<void> {
  const invite: FriendInvite = req.body;
  const senderId = new ObjectId(invite.from)
  const recipientId = new ObjectId(invite.to)

  if (!invite) {
    throw new Error(`Friend invite is not valid → ${invite}`)
  }

  const friend = await getUser({ _id: new ObjectId(recipientId) })
  const sender = await getUser({ _id: new ObjectId(senderId) })

  if (!friend) {
    throw new Error(`Friend not found → ${friend}`)
  } else if (!sender) {
    throw new Error(`User not found → ${sender}`)
  }

  const db = await getDb();
  const users = db.collection<User>('users')

  // Update the current user's friends list
  await users.updateOne(
    { _id: senderId },
    { $push: { friends: friend }}
  )
  await users.updateOne(
    { _id: senderId },
    { $pull: { friend_invites: { to: recipientId } } }
  )
  
  // Update the sender's friends list
  await users.updateOne(
    { _id: recipientId },
    { $push: { friends: sender }}
  )
  await users.updateOne(
    { _id: recipientId },
    { $pull: { friend_invites: { from: senderId } } }
  )

  res.status(200).json({ success: true, sender: sender })
}